[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet = "4TTQ3EVSM6D2zhQKSxZ4CtPAKTBQDockJRdH76c8u88e"
puppet_master = "7c4QnAEXSaiiPCo6E64eLjTBpXoFM7kgdHfmAb5bdryZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
tests = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "mocha"
